pyodbc.cpython-35m-x86_64-linux-gnu.so,sha256=OH6UFGa9UGne7JKsBKMIMp2Vbk4PgranNvWkFeXtBZk,570048
pyodbc-4.0.14.dist-info/DESCRIPTION.rst,sha256=zvBd0s-GAWA7NMmwHWkdPbRGltkhjHUiLpGLzUYkVWk,154
pyodbc-4.0.14.dist-info/METADATA,sha256=Q2NG3BVmf6xSIa628amI5GC9mdeG_cL1kwvqQr_Pqrk,848
pyodbc-4.0.14.dist-info/RECORD,,
pyodbc-4.0.14.dist-info/WHEEL,sha256=za7Wjm1blEPZrwcfJJm5AlNVXOyST9VKlUv9gs7rHC8,104
pyodbc-4.0.14.dist-info/metadata.json,sha256=hqyaWXhSbjdwkeZeO8K-QJI6dLZv31LLsmqit5K5CcQ,807
pyodbc-4.0.14.dist-info/top_level.txt,sha256=30jvYcCul6_wA26OT5c068GAHzqQLpd9WfQ0mSSsDTU,7
pyodbc-4.0.14.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
